# Generated by Django 3.2.5 on 2021-07-19 12:50

from django.db import migrations, models
import django.db.models.deletion
import hitmeapp.utils.models.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CryptoValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveIntegerField()),
                ('price', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('market_cap', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('volume', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('circulating_supply', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('percent_change_1h', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('percent_change_24h', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('percent_change_7d', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('percent_change_30d', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('percent_change_60d', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('percent_change_90d', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetservices.cryptocurrency')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
