# Generated by Django 3.2.5 on 2021-07-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitmeapp.utils.models.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('value_when_tracked', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('desired_value_type', models.CharField(choices=[('P', 'Percentage'), ('V', 'Value')], max_length=1)),
                ('desired_value', hitmeapp.utils.models.custom_fields.CurrencyField(decimal_places=8, max_digits=30)),
                ('notification_platform', models.CharField(choices=[('E', 'Email'), ('T', 'Telegram'), ('W', 'WhatsApp')], max_length=1)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetservices.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
