# Generated by Django 3.2.5 on 2021-07-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservices', '0002_auto_20210718_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptovalue',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptovalue',
            name='market_cap',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptovalue',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptovalue',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=30),
        ),
    ]
