# Generated by Django 3.2.5 on 2021-07-10 05:25

from django.db import migrations
import hitmeapp.users.models.users


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hitmeapp.users.models.users.UserManager()),
            ],
        ),
    ]
